databases:
  - name: Test data
    databaseName: test_database_jyxi
    user: test_database_postgres

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://test_database_postgres:RVkKuzbuQ7DVVnIUTxtDF2IvfOAM9emK@dpg-cj3mbtt9aq0e0q0078o0-a.oregon-postgres.render.com/test_database_jyxi
       name: mystest_database_jyxi
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50